/*
 *
 * Copyright © 2024 Applause App Quality, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */
package com.applause.auto.pageobjectmodel.elements;

import com.applause.auto.context.IPageObjectContext;
import com.applause.auto.pageobjectmodel.base.BaseElement;
import com.applause.auto.pageobjectmodel.base.LocatedBy;
import com.applause.auto.pageobjectmodel.factory.LazyWebElement;
import io.appium.java_client.ios.IOSDriver;

/**
 * BaseElement subclass representing a SegmentedControl - an iOS-specific UI element.
 *
 * @see com.applause.auto.pageobjectmodel.base.BaseElement
 */
public class SegmentedControl extends BaseElement {
  /**
   * Basic constructor for a SegmentedControl. SegmentedControls generally should be generated by
   * PageObjectBuilder.
   *
   * @param element the LazyWebElement underlying this SegmentedControl
   * @param context the web driver
   */
  public SegmentedControl(final LazyWebElement element, final IPageObjectContext context) {
    super(element, context);
  }

  /**
   * Gets the currently selected Button in the SegmentedControl.
   *
   * @return The currently selected button, as a Button element.
   */
  public Button getSelectedButton() {
    if (!(context.getDriver() instanceof IOSDriver)) {
      throw new UnsupportedOperationException(
          "SegmentedControl is an iOS-specific element. Not supported on " + "other platforms.");
    }
    return this.getChild(LocatedBy.iOSNsPredicate("value == '1'"), Button.class);
  }
}
