/*
 *
 * Copyright © 2024 Applause App Quality, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */
package com.applause.auto.pageobjectmodel.elements;

import com.applause.auto.context.IPageObjectContext;
import com.applause.auto.pageobjectmodel.base.BaseElement;
import com.applause.auto.pageobjectmodel.factory.LazyWebElement;
import io.appium.java_client.android.AndroidDriver;
import io.appium.java_client.ios.IOSDriver;

/**
 * BaseElement subclass representing a Switch on a mobile device.
 *
 * @see com.applause.auto.pageobjectmodel.base.BaseElement
 */
public class Switch extends BaseElement {
  /**
   * Basic constructor for a Switch. Switches generally should be generated by PageObjectBuilder.
   *
   * @param element the LazyWebElement underlying this Switch
   * @param context the underlying context
   */
  public Switch(final LazyWebElement element, final IPageObjectContext context) {
    super(element, context);
  }

  /**
   * Checks if the Switch is enabled. Overrides the BaseElement isEnabled() with a mobile device
   * version.
   *
   * @return true if switch is enabled, otherwise, false
   */
  @Override
  public boolean isEnabled() {
    if (context.getDriver() instanceof IOSDriver) {
      return "1".equals(this.underlying.getAttribute("value"));
    } else if (context.getDriver() instanceof AndroidDriver) {
      return Boolean.parseBoolean(this.underlying.getAttribute("checked"));
    }
    throw new UnsupportedOperationException(
        "Switches are only supported on Android and iOS drivers.");
  }
}
