name: Maven Publish Private

on:
  workflow_dispatch:
    inputs:
      javaVersion:
        description: "Java version to use"
        default: "21"
        type: string
      mavenProperties:
        description: "Maven properties to use"
        default: "-DskipGithub=true"
        type: string
      mavenTasks:
        description: "Maven tasks to use"
        default: "clean install deploy"
        type: string

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK ${{ inputs.javaVersion }}
        uses: actions/setup-java@v5
        with:
          java-version: "${{ inputs.javaVersion }}"
          distribution: "temurin"
      - name: Set up Maven
        uses: hb0730/maven-action@v1.0.2
        with:
          maven-version: 3.8.9

      - name: Create Maven settings.xml
        run: |
          cat << 'EOF' > $HOME/.m2/settings.xml
          <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                              https://maven.apache.org/xsd/settings-1.0.0.xsd">
            <servers>
                <server>
                    <id>s3.applause-private-repo</id>
                    <username>${{ secrets.APPLAUSE_REPO_USER_NAME }}</username>
                    <password>${{ secrets.APPLAUSE_REPO_PASSWORD }}</password>
                </server>
            </servers>

            <profiles>
              <profile>
                <activation>
                  <activeByDefault>true</activeByDefault>
                </activation>

                <repositories>
                  <repository>
                    <id>applause-repo</id>
                    <name>Repository for Applause private artifacts</name>
                    <url>https://repo.applause.com/repository/private</url>
                    <releases><enabled>true</enabled></releases>
                    <snapshots><enabled>true</enabled></snapshots>
                  </repository>
                  <repository>
                    <id>applause-public-repo</id>
                    <name>Repository for Applause public artifacts (releases)</name>
                    <url>https://repo.applause.com/repository/public</url>
                    <releases><enabled>true</enabled></releases>
                    <snapshots><enabled>false</enabled></snapshots>
                  </repository>
                </repositories>
                <pluginRepositories>
                  <pluginRepository>
                    <id>applause-public-repo</id>
                    <name>Repository for Applause public artifacts (releases)</name>
                    <url>https://repo.applause.com/repository/public</url>
                    <releases><enabled>true</enabled></releases>
                    <snapshots><enabled>false</enabled></snapshots>
                  </pluginRepository>
                </pluginRepositories>
              </profile>
            </profiles>
          </settings>
          EOF

      - name: Publish
        run: |
          mvn ${{ inputs.mavenProperties }} ${{ inputs.mavenTasks }}
